SG-34626 Escape for html characters
shotgunsoftware/tk-multi-launchapp pull request #96
Opened 2024-04-25 14:14 UTC by eduardoChaucaGallegos

Decorator created to escape html characters and also new log when exception happens and exists ui

2024-04-25 15:52 UTC, carlos-villavicencio-adsk reviewed
I think this solution can be much easier by just calling `html.escape` before showing the generic error message.

Let's wait for Julien's review to see what he thinks.

2024-04-25 15:56 UTC, eduardoChaucaGallegos commented
> I think this solution can be much easier by just calling `html.escape` before showing the generic error message.
> 
> Let's wait for Julien's review to see what he thinks.

I'm not pretty sure if the error than his fix is happening in another dialog or windows, that why I think that is good option to have a reusable decorator, and also for the future

2024-04-25 18:09 UTC, julien-lang requested changes
I agree with Carlos, I would like to explore the `html.escape` option too.
Also, could you add test(s) checking this case?

2024-04-30 15:34 UTC, julien-lang requested changes

2024-04-30 15:34 UTC, julien-lang commented on python/not_found_dialog/ui/dialog.py
I don't think the black reformating is useful in this PR since you did change anything in this file after all. If so, can you revert please to keep the PR as small as possible?

2024-04-30 15:34 UTC, julien-lang commented on python/tk_multi_launchapp/base_launcher.py
> +                self._tk_app.log_error(msg)
If we want to print this log whether or not there is UI, you can move the existing log line before the if block to avoid code duplication.

2024-05-14 16:35 UTC, carlos-villavicencio-adsk approved these changes
LGTM

2024-05-14 17:20 UTC, julien-lang approved these changes

2024-05-21 15:02 UTC, merged